#!/usr/bin/env bash

_docker_pick_container () {
  local tag_prefix="$1"
  docker ps | _fzf "${tag_prefix}" | _pick_first_col
}

_docker_pick_images () {
  docker images | awk '{print $1 ":" $2}' | _fzf $1
}

_consul_list_services_dns () {
  local domain="$1"
  local node="${2:-consul}"
  curl --fail --silent "http://$node.service.$domain:8500/v1/catalog/services" \
    | jq -r 'to_entries[] | .key, ({key, value: .value[]} | .value + "." + .key)' \
    | sed "s/$/\.service\.$domain/"
}

_chrome_parse_bookmarks () {
  jq -r \
     '.roots.bookmark_bar
      | recurse(.children[]?)
      | select(.type == "url")
      | "\(.url) | \(.name)"' \
     "$HOME/Library/Application Support/Google/Chrome/Default/Bookmarks"
}
