#!/usr/bin/env bash

_gcp_pick_project() {
  local query="${1:-}"
  gcloud projects list \
    | _fzf_pick "${query}"
}

_gcp_change_project() {
  local query="${1:-}"

  local project
  project="$(_gcp_pick_project "${query}")"
  gcloud config set project "${project}"
  _info "Now using ${project}"
}

__gcp_login() {
  gcloud auth login
  gcloud auth application-default login
}

_gcp_login() {
  _run_every 12h __gcp_login
}
