#!/usr/bin/env bash

_gcp_pick_project() {
  local query="$1"
  gcloud projects list --filter "name~${query}" --limit 10 \
    | _fzf_pick "${query}"
}

_gcp_change_project() {
  local query="$1"

  local project
  project="$(_gcp_pick_project "${query}")"
  gcloud config set project "${project}"
  _info "Now using ${project}"
}
