#!/usr/bin/env bash

_wrike() {
  local url_segment="$1"
  curl --silent --fail --globoff -X GET \
       --header "Authorization: bearer $(keyring get system wrike)" \
       "https://www.wrike.com/api/v3/${url_segment}"
}

_wrike_post() {
  local url_segment="$1"
  local payload="$2"
  curl --silent --fail -X POST \
       --header "Authorization: bearer $(keyring get system wrike)" \
       "https://www.wrike.com/api/v3/${url_segment}" -d "${payload}"
}

_wrike_put() {
  local url_segment="$1"
  local payload="$2"
  curl --silent --fail -g -X PUT \
       --header "Authorization: bearer $(keyring get system wrike)" \
       "https://www.wrike.com/api/v3/${url_segment}" -d "${payload}"
}

_wrike_user() {
  keyring get system wrike-user
}

_wrike_assigned_tasks() {
  _wrike "tasks/?responsibles=[$(_wrike_user)]&status=[Active]"
}

_wrike_all_tasks() {
  _wrike 'tasks?status=["Active"]' | __wrike_format_task
}

_wrike_branch() {
  _wrike_assigned_tasks | __wrike_format_task
}

__wrike_format_task() {
  jq -r '.data[] | "\(.permalink) \(.title)"' \
    | sed 's#https://www.wrike.com/open.htm?id=##'
}

__wrike_format_permalink() {
  jq -r '.data[0].permalink'
}

_wrike_current_task() {
  _wrike "tasks?permalink=https://www.wrike.com/open.htm?id=$(_git_current_issue_number)" \
    | jq -r '.data[0]'
}

_wrike_current_task_id() {
  _wrike "tasks?permalink=https://www.wrike.com/open.htm?id=$(_git_current_issue_number)" \
    | jq -r '.data[0].id'
}

_wrike_new_children_assigned() {
  local title="$1"
  local description="$2"
  __wrike_new "title=${title}&description=${description}&superTasks=[\"$(_wrike_current_task_id)\"]&responsibles=[\"$(_wrike_user)\"]"
}

_wrike_new_children() {
  local title="$1"
  local description="$2"
  __wrike_new "title=${title}&description=${description}&superTasks=[\"$(_wrike_current_task_id)\"]"
}

_wrike_new() {
  local title="$1"
  local description="$2"
  __wrike_new "title=${title}&description=${description}"
}

_wrike_new_current() {
  local title="$1"
  local description="$2"
  __wrike_new "title=${title}&description=${description}&responsibles=[\"$(_wrike_user)\"]" 'IEABJUC4I4DUMKMP'
}

_wrike_new_idea() {
  local title="$1"
  local description="$2"
  __wrike_new "title=${title}&description=${description}" 'IEABJUC4I4EB427E'
}

__wrike_new() {
  local payload="${1}"
  local folder="${2:-IEABJUC4I4DYI2CA}"
  _wrike_post "folders/${folder}/tasks" "${payload}" \
    | jq -r '.data[0].permalink'
}

_wrike_open() {
  open "$(_wrike "tasks/$(_wrike_current_task_id)" | __wrike_format_permalink)"
}

_wrike_format_text() {
  pandoc -f html -t markdown | sed 's/\\$//g'
}

_wrike_comments() {
  local task_id
  task_id="$(_wrike_current_task_id)"

  _wrike "tasks/${task_id}" \
    | jq -r '.data[0] | "\(.title)<br><br>\(.description)"' \
    | _wrike_format_text

  _wrike "tasks/${task_id}/comments" \
    | jq -r '.data[] | "\(.authorId) \(.createdDate)<br>\(.text)"' \
    | _wrike_format_text
}

_wrike_folders() {
  _wrike 'folders' \
    | jq -r '.data[] | "\(.id) \(.title)"'
}

_wrike_change_status() {
  local custom_status="$1"
  _wrike_put "tasks/$(_wrike_current_task_id)" "customStatus=${custom_status}" | __wrike_format_permalink
}

_wrike_wip() {
  _wrike_change_status 'IEABJUC4JMACWQ6I'
}

_wrike_complete() {
  _wrike_change_status 'IEABJUC4JMACWQ5L'
}
