#!/usr/bin/env bash

set -o errexit
set -o pipefail


_main() {
  osascript -e 'tell application "Emacs" to activate' > /dev/null 2>&1 &
  if [[ "$1" == '+' ]]; then
    # workaround iTerm semantic opening.
    exec emacsclient --no-wait "${@:2}" > /dev/null 2>&1 &
  elif [[ "$1" == '-' ]]; then
    tempfile="$(mktemp emacs-stdin-$USER.XXXXXXX)"
    cat - > "${tempfile}"
    exec emacsclient -e "(progn (find-file \"${tempfile}\")
                             (set-visited-file-name nil)
                             (rename-buffer \"*stdin*\" t))
                 " 2>&1 > /dev/null
  else
    exec emacsclient --no-wait "$@" > /dev/null 2>&1 &
  fi
}

_main "$@"
