#!/usr/bin/env bash

set -o errexit
set -o pipefail


_main() {
  osascript -e 'tell application "Emacs" to activate' > /dev/null 2>&1 &
  if [[ "$1" == '+' ]]; then
    # Workaround iTerm semantic opening.
    _emacs "${@:2}"
  elif [[ "$1" == '-' ]]; then
    # Support piping text to emacs.
    local tempfile
    tempfile="$(mktemp -t "emacs-stdin-$USER")"
    cat - > "${tempfile}"
    _emacs "${tempfile}"
  else
    _emacs "$@"
  fi
}

_get_brew_prefix() {
  local brew_prefix='/opt/homebrew'
  if [[ ! -d "${brew_prefix}" ]]; then
    brew_prefix="/usr/local"
  fi
  echo "${brew_prefix}"
}

_emacs() {
  exec "${BREW_PREFIX:-$(_get_brew_prefix)}/bin/emacsclient" --no-wait "$@" > /dev/null 2>&1 &
}

_main "$@"
