#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -u

# Set LOG=anything to debug iTerm...
readonly LOG

_main() {
  local filepath="$1"
  local line_number="${2:-}"
  local column_number="${3:-}"

  case "${filepath}" in
    *.scala|*.java|*.sbt|*pom.xml|*.tsx|*.tf|*.py)
      if [[ -n "${line_number}" ]]; then
        _idea "${filepath}:${line_number}"
      else
        _idea "${filepath}"
      fi
      ;;
    *)
      if [[ -n "${line_number}" ]]; then
        _emacs "+${line_number}:${column_number}" "${filepath}"
      else
        _emacs "${filepath}"
      fi
      ;;
  esac
}

_emacs() {
  _exec "${BREW_PREFIX}/bin/emacsclient" --no-wait "$@"
}

_idea() {
  _exec /usr/local/bin/idea "$@"
}

_exec() {
  _log "$@"
  exec "$@" 2>&1 &
}

_log() {
  if [[ -n "${LOG:-}" ]]; then
    echo "$*" >> "$HOME/.editor.log"
  fi
}

_log 'Arguments:' "$@"
_main "$@"
