#!/usr/bin/env bash

set -o errexit
set -o pipefail

source "$HOME/.functions/base"
source "$HOME/.functions/git"

_format () {
    jq -r '"\(.created_at) - \(if has("pull_request") then "PR | " else "" end)\(.title) \(.html_url)"'
}

_github_involved_issues \
    | _format \
    | sort -ur
