#!/usr/bin/env bash

set -o errexit
set -o pipefail

source "$HOME/.functions/base"
source "$HOME/.functions/git"

_unpack () {
  jq -rc '.[]'
}

_filter () {
    grep "PullRequestEvent\|$(_github_user)"
}

_format () {
  jq -rc '. | [
    .created_at,
    .payload.pull_request.html_url // .payload.issue.html_url // "https://github.com/\(.repo.name)",
    "|\(.type | sub("Event"; "")) \(.payload.action // "") by \(.actor.login) => ",
    (.payload |
      ((.issue // .pull_request) | .user.login, (.assignees[]? | .login)),
      "|\(.issue // .pull_request | .title // .ref // "N/A") => \(.comment // .pull_request // .issue | .body // "N/A")"
    )] | join(" ") | sub("\n|\r|  |\t"; " "; "g")'
}

_cached _github_events \
  | _unpack \
  | _filter \
  | _format \
  | column -s '|' -t \
  | cut -c "-${COLUMNS:-200}"
