#!/usr/bin/env bash

set -o errexit
set -o pipefail

source "$HOME/.functions/base"
source "$HOME/.functions/git"

_filter () {
  jq -rc '.[]' \
    | grep "PullRequestEvent\|$(_github_user)"
}

_format () {
  jq -rc '. | [
    .created_at,
    .payload.pull_request.html_url // .payload.issue.html_url // "https://github.com/\(.repo.name)",
    "|\(.type | sub("Event"; "")) \(.payload.action // "") by \(.actor.login) - ",
    (.payload |
      ((.issue // .pull_request) | .user.login, (.assignees[]? | .login)),
      "|\(.issue // .pull_request | .title // .ref // "") \(.comment // .pull_request // .issue | .body // "")"
    )] | join(" ") | sub("\n|\r|  |\t"; " "; "g")'
}

_cached _github_events \
  | _filter \
  | _format \
  | column -s '|' -t \
  | cut -c "-${COLUMNS:-200}"
