#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -u

_show_command() {
  _info "Executing: $*"
  "$@"
}

_info() {
  echo >&2 "[info] $*"
}

_fatal() {
  local message="$1"
  local code="${2:-255}"
  echo >&2 "[fatal] ${message} Exit code: ${code}"
  exit "${code}"
}

_get_instance() {
  local instance_name="$1"
  gcloud compute instances list --filter "${instance_name}" \
    | fzf -0 -1 --header-lines=1 \
    | awk '{ print "--zone " $2 " " $1}'
}

_usage() {
  cat >&2 << EOF
SSH via GCP IAP

  $0 INSTANCE_NAME [SSH ARGS]

Example:
  $ rsync -ave $0 local-path instance-name:remote-path'
  $ $0 instance-name -T <<< 'hostname'

EOF
}

_main() {
  local instance_name=''
  local key="$1"
  ssh_args=()
  case "${key}" in
    -h | --help | h | help)
      _usage
      exit 0
      ;;
    -t | --tmux)
      if [[ "${TERM_PROGRAM:-}" =~ 'iTerm' ]]; then
        ssh_args+=('-t' "command; tmux -CC new-session -A -s ${USER}")
      else
        ssh_args+=('-t' "command; tmux new-session -A -s ${USER}")
      fi
      ;;
    -*)
      _fatal "Invalid flag: ${key}"
      ;;
    *)
      instance_name="${key}"
  esac
  shift || true

  if [[ "$#" -eq 1 ]]; then
    instance_name="$1"
    shift
  fi


  if [[ -z "${instance_name}" ]]; then
    _usage
    exit 255
  fi

  # shellcheck disable=SC2046
  # We want to expand unquoted arguments from _get_instance here.
  _show_command exec gcloud compute ssh \
                --tunnel-through-iap \
                $(_get_instance "${instance_name}") \
                -- "${ssh_args[@]}" \
                "$@"
}

_main "$@"
