#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -u

IFS=$'\n\t'

_info() {
  echo >&2 "[info] $*"
}

_fatal() {
  local message="$1"
  local code="${2:-255}"
  echo >&2 "[fatal] ${message} Exit code: ${code}"
  exit "${code}"
}

__k8s_current_context() {
  kubectl config view --minify --output json \
    | jq -r '.contexts[0].context | "cluster: \(.cluster) namespace: \(.namespace)"'
}

_kubectl() {
  _info "Running 'kubectl $(tr -d '\n' <<< "$@")' on $(__k8s_current_context)"
  kubectl "$@"
}

_gcp_k8s_auth() {
  local project="$1"
  gcloud container clusters list --project "${project}" --format json \
    | jq -r '.[] | "\(.name)  --zone \(.zone)"' \
    | xargs -n3 gcloud container clusters get-credentials --project "${project}"
}

_fzf_pick() {
  local query="$1"
  fzf -0 -1 --header-lines=1 --query "'${query}" \
    | awk '{print $1}' || {
    _fatal "Could not find '${query}'"
  }
}

_k8s_pick_resource() {
  local resource_type="$1"
  local resource="$2"
  _kubectl get "${resource_type}" | _fzf_pick "${resource}"
}

_k8s_command_pick_resource() {
  local command="$1"
  local resource_type="$2"
  local resource="${3:-}"
  if [[ "${resource}" == 'all' ]]; then
    _kubectl "${command}" "${resource_type}" "${@:4}"
  else
    _kubectl "${command}" "${resource_type}" "$(_k8s_pick_resource "${resource_type}" "${resource}")" "${@:4}"
  fi
}

_k8s_pick_pod() {
  _k8s_pick_resource 'pod' "$@"
}

_k8s_switch_cluster() {
  local context="${1:-}"
  context="$(
    _kubectl config get-contexts \
      | fzf -0 -1 --header-lines=1 --query "'${context}" \
      | awk '{print $2}'
  )"

  kubectl config use-context "${context}"
  _info "Now on $(__k8s_current_context)"
}

_k8s_switch_namespace() {
  local namespace="${1:-}"
  namespace="$(_k8s_pick_resource namespace "${namespace}")"
  _info "Switching namespace to: ${namespace}..."
  _kubectl config set-context --current --namespace="${namespace}"
}

_k8s_exec() {
  local pod="${1:-}"
  pod="$(_k8s_pick_pod "${pod}")"
  _kubectl exec -it "${pod}" "${2:-/bin/bash}" "${@:3}"
}

_k8s_logs() {
  __k8s_logs "${1:-}" "${@:2}" --all-containers --follow=true --tail=100
}

__k8s_logs() {
  local pod="${1:-}"
  _kubectl logs "$(_k8s_pick_pod "${pod}")" "${@:2}"
}

_usage() {
  cat >&2 << EOF
USAGE: $0 COMMANDS [OPTIONS]...

Wrapper around kubectl.

A RESOURCE_TYPE is a pod, a deployment, service, etc.

COMMANDS:
EOF

  grep --extended-regexp '^    [[:alnum:]-]+.*)' "$0" \
    | sed 's/^  //; s/ |/,/g; s/)//; s/# //'
}

_main() {
  local key="${1:-}"
  shift || true
  case "${key}" in
    -h | --help | h | help) # Show help/usage.
      _usage
      exit 0
      ;;
    auth) # [PROJECT] Authenticate/add all cluster in the specified project.
      _gcp_k8s_auth "$@"
      ;;
    d | describe) # RESOURCE_TYPE [RESOURCE_NAME] Describe the chosen resource. Will list resources if there no exact match or no resource passed.
      _k8s_command_pick_resource describe "$@"
      ;;
    ed | edit) # RESOURCE_TYPE [RESOURCE_NAME] Edit the chosen resource. Will list resources if there no exact match or no resource passed.
      _k8s_command_pick_resource edit "$@"
      ;;
    e | exec) # [POD_NAME] Run bash or other command on pod. Will list pods if there no exact match or no resource passed.
      _k8s_exec "$@"
      ;;
    g | get) # ARGS kubectl get ...
      _kubectl get "$@"
      ;;
    gr | get-resource) # [RESOURCE_TYPE] Get all resource. Will list resource types if there no exact match or no resource passed.
      _kubectl get "$(_kubectl api-resources | _fzf_pick "${1:-}")"
      ;;
    gry | get-resource-yaml) # [RESOURCE_TYPE] Get all resource as yaml for a specific resource type. Will list resource types if there no exact match or no resource passed.
      _k8s_command_pick_resource get "$(_kubectl api-resources | _fzf_pick "${1:-}")" "${2:-}" "${@:3}" --output=yaml
      ;;
    gy | get-yaml) # RESOURCE_TYPE [RESOURCE_NAME] Get yaml output of the chosen resource. Will list resources if there no exact match or no resource passed.
      _k8s_command_pick_resource get "$1" "${2:-}" "${@:3}" --output=yaml
      ;;
    l | logs) # [POD] Watch logs for all containers in pod.
      _k8s_logs "$@"
      ;;
    sc | switch-cluster) # [CLUSTER/CONTEXT] Will list clusters/contexts if there no exact match or no cluster is passed.
      _k8s_switch_cluster "$@"
      ;;
    sn | switch-namespace) # [NAMESPACE] Will list namespace if there no exact match or no namespace is passed.
      _k8s_switch_namespace "$@"
      ;;
    --) # ARGS   Pass arguments directly to kubectl
      _kubectl "$@"
      ;;
    *) # ARGS   Pass arguments directly to kubectl
      _kubectl "${key}" "$@"
      ;;
  esac
}

_main "$@"
