#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -u

_info() {
  echo >&2 "[info] $*"
}

_sync_external_services() {
  pushd "$HOME/.bin"

  _info 'Syncing calendars...'
  ./org-sync-calendar

  _info 'Syncing todoist...'
  poetry run python org-sync-todoist

  _info 'Syncing pushbullet...'
  poetry run python org-sync-pushbullet

  popd
}

_sync_repository() {
  pushd "$HOME/.org"

  git status \
    || sleep 1

  git add '.'

  git commit -m "Sync from $(hostname) at $(gdate --iso-8601=minutes)" \
    || true

  _info 'Pulling from repo...'
  git pull

  _info 'Pushing to repo...'
  git push

  popd
}

_main() {
  if [[ "${ORG_SYNC_EXTERNAL_SERVICES:-}" == 'true' ]]; then
    _info 'Syncing with external services...'
    _sync_external_services
  else
    _info 'Skipping syncing with external services since ORG_SYNC_EXTERNAL_SERVICES is not "true".'
  fi

  _sync_repository

  _info 'Done!'
}

_main
