#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
from subprocess import run
from urllib import parse


def main():
    content = {"url": f"file+emacs:{sys.argv[1]}"}

    if len(sys.argv) > 2:
        content["title"] = sys.argv[2]
    else:
        content["title"] = sys.argv[1]

    if len(sys.argv) > 3:
        content["body"] = sys.argv[3]

    url = f"org-protocol://capture?{parse.urlencode(content)}"

    run(["osascript", "-e", 'tell application "Emacs" to activate'])
    run(["/usr/local/bin/emacsclient", "--quiet", "--no-wait", url])


if __name__ == "__main__":
    main()
